logging:
  file: "logs/nav_base.log"

server:
  port: 8081
  servlet:
    context-path: /${spring.application.name}

spring:
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB  
      location: /Users/zhangjunliang/download/
  application:
    name: nav_base
  datasource:
    nav:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.88.7.236:3306/pvsky_nav?useSSL=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
      username: xxx
      password: Ci9saVQrxAZ
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000